export enum AuditLogType {
  Info = 1,
  Warning = 2,
  Error = 3,
  ChannelCreated = 5,
  ChannelDeleted = 6,
  ChannelUpdated = 7,
  EmoteDeleted = 8,
  OverwriteCreated = 9,
  OverwriteDeleted = 10,
  OverwriteUpdated = 11,
  Unban = 12,
  MemberUpdated = 13,
  MemberRoleUpdated = 14,
  GuildUpdated = 15,
  UserLeft = 16,
  UserJoined = 17,
  MessageEdited = 18,
  MessageDeleted = 19,
  InteractionCommand = 20,
  ThreadDeleted = 21,
  JobCompleted = 22,
  Api = 23,
  ThreadUpdated = 24,
  RoleDeleted = 25,
  MemberWarning = 26
}
