import * as icons from '@coreui/icons';

export const iconSubset = {
  cibDiscord: icons.cibDiscord,
  cibGithub: icons.cibGithub,
  cibSwagger: icons.cibSwagger,
  cilAccountLogout: icons.cilAccountLogout,
  cilArrowRight: icons.cilArrowRight,
  cilBook: icons.cilBook,
  cilCheckCircle: icons.cilCheckCircle,
  cilContrast: icons.cilContrast,
  cilMenu: icons.cilMenu,
  cilMoon: icons.cilMoon,
  cilSpeech: icons.cilSpeech,
  cilSpeedometer: icons.cilSpeedometer,
  cilSun: icons.cilSun,
  cilUser: icons.cilUser,
  cilClock: icons.cilClock,
  cilPowerStandby: icons.cilPowerStandby,
  cilMemory: icons.cilMemory,
  cilXCircle: icons.cilXCircle,
  cilSitemap: icons.cilSitemap,
  cilWarning: icons.cilWarning,
  cilFeaturedPlaylist: icons.cilFeaturedPlaylist,
  cilBarChart: icons.cilBarChart,
  cilShieldAlt: icons.cilShieldAlt,
  cilTerminal: icons.cilTerminal,
  cibProbot: icons.cibProbot,
  cilChatBubble: icons.cilChatBubble,
  cilSearch: icons.cilSearch,
  cilArrowThickLeft: icons.cilArrowThickLeft,
  cilArrowThickToLeft: icons.cilArrowThickToLeft,
  cilArrowThickRight: icons.cilArrowThickRight,
  cilArrowThickToRight: icons.cilArrowThickToRight,
  cilSmile: icons.cilSmile,
  cilShare: icons.cilShare,
  cilDescription: icons.cilDescription,
  cilEnvelopeOpen: icons.cilEnvelopeOpen,
  cilCommentSquare: icons.cilCommentSquare,
};
